name: Build

on:
  push:
    branches:
      - '*'
      - 'master'
      - 'add_internal_storage'
  pull_request:
    branches:
      - '*'
      - 'master'
      - 'add_internal_storage'

jobs:
  compile:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.sm-version == '1.11.x' }}
    strategy:
      matrix:
        sm-version: [ '1.9.x', '1.10.x', '1.11.x' ]
        # compiler-options: [ '', '__MADEBUG=1' ]
    
    env:
      DEBUG: ${{ contains(matrix.compiler-options, '__XDEBUG=1') }}

    name: "Build SM ${{ matrix.sm-version }} ${{ matrix.compiler-options != '' && format('({0})', matrix.compiler-options) || '' }}"
    steps:
      - uses: actions/checkout@v2

      - name: Setup SP
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.sm-version }}

      - name: Run compiler
        run: |
          cd addons/sourcemod
          mkdir plugins
          cd scripting
          spcomp VIP_Core.sp -E -o ../plugins/VIP_Core.smx -iinclude ${{ matrix.compiler-options }}
      
      # - name: Make artifact archive
      #   if: github.ref == 'refs/heads/master'
      #   run: |         
      #     if [[ "$DEBUG" == "true" ]]; then export CUSTOM_POSTFIX="d"; fi
      #     SMVERSION_FULL=${{ matrix.sm-version }}
          
      #     export SMVERSION_SHORT=${SMVERSION_FULL:0:-2}
      #     export ARCHIVE_FILENAME=sbma-newplugin.${GITHUB_SHA::7}.${SMVERSION_SHORT}${CUSTOM_POSTFIX}.tar.gz
          
      #     echo "ARCHIVE_FILENAME=$ARCHIVE_FILENAME" >> $GITHUB_ENV
      #     echo "SMVERSION_SHORT=$SMVERSION_SHORT" >> $GITHUB_ENV
          
      #     tar -cvf $ARCHIVE_FILENAME addons
      
      - name: Upload artifact
       uses: actions/upload-artifact@v3
        with:
          name: VIP-Core
          path: addons
